### ISSUE TITLE
Drawing arrows does not seem to work properly

### ISSUE THREAD

**Issue by mstill3** [poliastro/czml3#100]
I may be trying to accomplish this improperly:
 
 ```
 Packet(
            id="Arrow/Arrow-" + str(uuid.uuid4()),
            name="Arrow",
            polyline=Polyline(
                positions=positions,
                material=PolylineArrowMaterial(color=Color(rgba=[200, 100, 30, 255])),
                arcType="NONE",
                width=width
            )
        )
```
![image](https://user-images.githubusercontent.com/18670089/148595812-eec3efbc-4b9f-40a9-b12f-73d44fbce888.png)

**Comment by astrojuanlu** [comment]
Hi @mstill3 ! I think this should be the correct way:

```python
Polyline(
    material=PolylineMaterial(
        polylineArrow=PolylineArrowMaterial(
            color=Color(rgba=[200, 100, 30, 255])
        )
    )
)
```

however, it looks like `PolylineMaterial` does not support `polylineArrow`:

https://github.com/poliastro/czml3/blob/ab7d7eb7d8d7b97c088cca818d5fc989f02e19c6/src/czml3/properties.py#L75-L84

(I am extremely confused because I suggested this same snippet to @mhaberler in https://github.com/poliastro/czml3/pull/80#issuecomment-745632263 one year ago and I don't understand how did we make it work, because I didn't find anywhere in the git history the `polylineArrow` property 😳)

Would you like to send a pull request?

**Comment by astrojuanlu** [comment]
I understand that this is fixed by #103, let me know otherwise! Can you paste a fragment of working code with a screenshot for proof?

**Comment by mstill3** [comment]
Here you go
![outline1](https://user-images.githubusercontent.com/18670089/148851290-21194704-1b50-4ce1-a5df-fcca7dc41d5b.PNG)
![arrow1](https://user-images.githubusercontent.com/18670089/148851294-ab10efab-350b-4dbe-aaa3-f134e829474a.PNG)
![dash1](https://user-images.githubusercontent.com/18670089/148851296-82527c4b-8a8f-4ee5-9750-13edd1996483.PNG)
![glow1](https://user-images.githubusercontent.com/18670089/148851298-83864cfa-7d04-4366-99d8-0197cca40c04.PNG)
:

**Comment by astrojuanlu** [comment]
Awesome, thanks! Closing
