### ISSUE TITLE
Add version to czml3

### ISSUE THREAD

**Issue by Stoops-ML** [poliastro/czml3#109]
The czml3 package doesn't have a version. I propose [Semantic Versioning](https://semver.org/): major.minor.patch.

Further, what should the current version be? 1.0.0 probably makes the most sense as it seems like czml3 is very much out of beta testing.

I'll do a PR once a decision has been made.

**Comment by astrojuanlu** [comment]
It does have a version: it comes from the git tag.

https://github.com/poliastro/czml3/blob/feb7f0a946ac12bb92a4ac332a3fe83853e45263/setup.py#L5

It's 0.7.0 now https://pypi.org/project/czml3/0.7.0/

I'd say 1.0 should be for the moment czml3 implements all of CZML, I'd say. But I'm not actively maintaining it (as you have probably noticed already) so I'm open to being persuaded otherwise.

In any case, if we don't change anything, next version will be 0.8.0. @Stoops-ML if that sounds OK, feel free to close this issue.

**Comment by Stoops-ML** [comment]
Apologies, you're right. This is the first time I've worked with `versioneer` before.

I'm planning on adding some more features to your package - so perhaps hold off from bumping the version 0.8.0. Hopefully I'll have them ready in the next few days.
