### ISSUE TITLE
[feature request] Allow `dict` types for value field in `IntervalValue`

### ISSUE THREAD

**Issue by vishwa2710** [poliastro/czml3#150]
Hello!

I was trying to recreate the [simple.czml](https://github.com/CesiumGS/cesium/blob/main/Apps/SampleData/simple.czml) example. Specifically, the polylines with the leadTime and trailTime fields.
Using CZML3, this requires creating an `IntervalValue` object as follows:
```
    IntervalValue(
        start="2012-03-15T15:21:48.776005533Z",
        end="2012-03-15T16:54:06.33371177400113Z",
        value={
                "epoch": "2012-03-15T15:21:48.776005533Z",
                "number": [0, 0, 5537.557706241001, 5537.557706241001],
            }
    )
```
However, this is not possible due to how the `to_json` function is currently implemented for the `IntervalValue` object.

Here is a proposed fix for this issue: https://github.com/poliastro/czml3/pull/149. Let me know what you think!

**Comment by astrojuanlu** [comment]
Wdyt @Stoops-ML ?

**Comment by Stoops-ML** [comment]
Just tried this out and indeed @vishwa2710's example raises an error as the `value` field doesn't support `dict` types:

```
> a = IntervalValue(
        start="2012-03-15T15:21:48.776005533Z",
        end="2012-03-15T16:54:06.33371177400113Z",
        value={
                "epoch": "2012-03-15T15:21:48.776005533Z",
                "number": [0, 0, 5537.557706241001, 5537.557706241001],
            }
    )
> a.to_json()
 
Traceback (most recent call last):
  File "C:\Users\danielst\Projects\python_packages\czml3\src\czml3\types.py", line 347, in to_json
    obj_dict.update(**self._value.to_json())
                      ^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'to_json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\danielst\Projects\python_packages\czml3\src\czml3\types.py", line 349, in to_json
    key = TYPE_MAPPING[type(self._value)]
          ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: <class 'dict'>
```

What's the reason behind the `value` field in `IntervalValue`? There's disparity between the [Path](https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/Path) documentation for `leadTime` and the [simple.czml](https://github.com/CesiumGS/cesium/blob/7b93161da1cc03bdc796b204e7aa51fb7acebf04/Apps/SampleData/simple.czml#L422C7-L430C10) example, so my guess is that the `value` field is meant to bridge any gaps.

**Comment by vishwa2710** [comment]
Yes I agree the documentation is not quite clear on this. I found this thread that further explains it: https://community.cesium.com/t/leadtime-and-trailtime-in-simple-czml/2749
Since `IntervalValue` is meant as a catch-all for multiple types of fields, I figured this was a clean solution but I might have misunderstood what the purpose of the value field was.

This does not protect us from the case where the provided dict contains fields that are not JSON serializable.

An alternative solution would be to create a new type called `TimeValue` or something, which is then an epoch + numbers.
```
class TimeValue:

    def __init__(self, epoch, number):
        self.epoch = epoch
        self.number = number

    def to_json(self):
        return {
            "epoch": self.epoch,
            "number": self.number,
        }
```
Something like that, so it's more explicit.

**Comment by Stoops-ML** [comment]
From [simple.py](https://github.com/poliastro/czml3/blob/136094490187128d608316d54ac9b9b1b366cf79/src/czml3/examples/simple.py#L31) and [simple.czml](https://github.com/CesiumGS/cesium/blob/7b93161da1cc03bdc796b204e7aa51fb7acebf04/Apps/SampleData/simple.czml#L422C7-L430C10) it seems that the purpose of the `IntervalValue` type is to create an `interval` on the `value` that is passed to it.

The [current implementation](https://github.com/poliastro/czml3/blob/136094490187128d608316d54ac9b9b1b366cf79/src/czml3/types.py#L346) of the handling of `value` in `IntervalValue` is essentially:
1. If the object passed is a `BaseCZMLObject` then append the properties of the object to the `interval`.
2. Otherwise, add a new field where the key is the value type and the value is the value passed.

The solution in #149 allows the user to create their own CZML types (i.e. passing a `dict` with whatever they want inside). This seems to me to go against the philosophy of czml3: every CZML property and type has a corresponding class in czml3.

I would suggest:
1. Adding an `epoch` and `number` types
2. Modifying `IntervalValue.to_json` to handle a sequence of `BaseCZMLObject` objects

Thoughts?

**Comment by vishwa2710** [comment]
That's fair. If that is the intended philosophy then I agree it is definitely counter that.
IMO this requires creating a lot more boilerplate code within the repository, I bypassed this issue by creating a dummy class like above and passing that, as it has a `to_json` function.

However, creating these types does provide some type safety which is nice.

Let me take a crack at it in #149 and see how it looks. Thanks for the swift discussion and advice @astrojuanlu and @Stoops-ML !

**Comment by Stoops-ML** [comment]
Great to see that you’re getting involved! Any and all improvements to this package is greatly appreciated. 

Please open another PR with the new method. I’d like to keep your previous PR separate for reference.

**Comment by vishwa2710** [comment]
Okay here's the idea with numbers and epoch as separate type values:
https://github.com/poliastro/czml3/pull/151

**Comment by Stoops-ML** [comment]
Closing as #151 merged.
